- name: Download Servarr Backups from ullrservarr and upload to Proton Drive
  hosts: localhost
  gather_facts: true
  vars:
    services:
      - radarr
    remote_path_base: "/opt/nas/apps"
    today: "{{ ansible_date_time.date }}"
    local_backup_root: "/tmp/ansible_vm_backups/{{ today }}"
    proton_remote: "proton-remote"
    retention_count: 5

  tasks:
    - name: Ensure local backup root exists for each service
      file:
        path: "{{ local_backup_root }}/{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ services }}"

    - name: Find latest backup path on remote host for each service
      shell: "ls -t {{ remote_path_base }}/{{ item }}/Backups/scheduled/*.zip | head -n 1"
      delegate_to: ullrservarr
      register: latest_backups
      retries: 3
      delay: 5
      until: latest_backups.rc == 0
      loop: "{{ services }}"
      loop_control:
        label: "{{ item }}"

    - name: Debug latest backup paths gathered from remote host
      debug:
        msg: "{{ latest_backups.results | map(attribute='stdout') | list }}"

    - name: Set fact mapping each service to its remote backup file path
      set_fact:
        service_backups: "{{ dict(services | zip(latest_backups.results | map(attribute='stdout') | list)) }}"

    - name: Set fact for backup filenames (basename of remote file)
      set_fact:
        service_backup_names: "{{ dict(services | zip(latest_backups.results | map(attribute='stdout') | map('basename') | list)) }}"

    - name: Fetch backup file from remote host for each service
      fetch:
        src: "{{ item.value }}"
        dest: "{{ local_backup_root }}/{{ item.key }}/"
        flat: yes
      delegate_to: ullrservarr
      loop: "{{ service_backups | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      register: fetch_result
      retries: 3
      delay: 5
      until: fetch_result is success

    - name: Upload backup file to Proton Drive for each service (no date folder)
      shell: >
        rclone copy
        "{{ local_backup_root }}/{{ item }}/{{ service_backup_names[item] }}"
        "{{ proton_remote }}:backups/{{ today }}/{{ item }}"
      loop: "{{ services }}"
      loop_control:
        label: "{{ item }}"
      environment:
        RCLONE_CONFIG_FILE: "/home/hrolgar/.config/rclone/rclone.conf"

    - name: Cleanup old backups in Proton Drive
      shell: |
        rclone lsjson "{{ proton_remote }}:backups/" --recursive |
        jq -r '.[] | select(.Path | test("{{ item }}-backup-\\d{4}-\\d{2}-\\d{2}\\.zip$")) | .Path' |
        sort -r | tail -n +{{ retention_count + 1 }} |
        xargs -r -I {} rclone delete "{{ proton_remote }}:backups/{}"
      loop: "{{ services }}"
      loop_control:
        label: "{{ item }}"
      environment:
        RCLONE_CONFIG_FILE: "/home/hrolgar/.config/rclone/rclone.conf"

    - name: Remove local backups
      file:
        path: "{{ local_backup_root }}"
        state: absent
      ignore_errors: true
