- name: Download Servarr Backups from ullrservarr and upload to Proton Drive
  hosts: localhost
  gather_facts: false
  vars:
    services:
      - radarr
    remote_path_base: "/opt/nas/apps"
    local_backup_root: "/tmp/servarr_backups/{{ today }}"
    proton_remote: "proton-remote"
    today: "{{ ansible_date_time.date }}"
    retention_count: 5

  tasks:
    - name: Find latest backup path on remote host for each service
      shell: "ls -t {{ remote_path_base }}/{{ item }}/Backups/scheduled/*.zip | head -n 1"
      delegate_to: ullrservarr
      register: latest_backups
      retries: 3
      delay: 5
      until: latest_backups.rc == 0
      loop: "{{ services }}"
      loop_control:
        label: "{{ item }}"

    - name: Debug latest backups paths gathered from remote host
      debug:
        msg: "{{ latest_backups.results | map(attribute='stdout') | list }}"
