- name: Update Aliases on All VMs
  hosts: all
  become: yes
  tasks:
    - name: Ensure Git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Clone or update aliases repository
      ansible.builtin.git:
        repo: 'https://github.com/Hrolgar/ansible-playbook.git'
        dest: ~/ansible-playbook
        update: yes
        version: main

    - name: Move alias file to the correct location
      ansible.builtin.shell: |
        cp ~/ansible-playbook/shared/aliases.txt ~/.my_aliases
      args:
        executable: /bin/bash

    - name: Ensure .bashrc sources .my_aliases
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        create: yes
        line: 'source ~/.my_aliases'
        state: present
        insertafter: EOF

    - name: Source the updated aliases
      ansible.builtin.shell: source ~/.bashrc
      args:
        executable: /bin/bash
