- hosts: proxmox_vms
  become: yes
  become_method: sudo
  tasks:
    - name: Test sudo privileges
      command: sudo -n true
      register: sudo_test
      ignore_errors: yes
      changed_when: sudo_test.rc != 0
    
    - name: Update apt cache and upgrade all packages
      become: yes
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if required
      reboot:
        msg: "Reboot initiated by Ansible after updates."
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists
