- name: Update Aliases on All VMs
  hosts: all
  become: yes
  tasks:
    - name: Ensure Git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Clone or update aliases repository
      ansible.builtin.git:
        repo: 'https://github.com/Hrolgar/ansible-playbook.git'
        dest: /root/ansible-playbook
        update: yes
        version: main

    - name: List files in shared folder before copying
      ansible.builtin.shell: ls -lah /root/ansible-playbook/shared
      register: shared_files
      args:
        executable: /bin/bash

    - name: Show shared folder contents
      ansible.builtin.debug:
        var: shared_files.stdout

    - name: Move alias file to the correct location
      ansible.builtin.shell: |
        cp /root/ansible-playbook/shared/aliases.txt {{ ansible_user_dir }}/.my_aliases
        ls -lah {{ ansible_user_dir }}/.my_aliases
      register: copy_result
      args:
        executable: /bin/bash

    - name: Show result of copying aliases file
      ansible.builtin.debug:
        var: copy_result.stdout

    - name: Ensure .bashrc sources .my_aliases
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        create: yes
        line: 'source ~/.my_aliases'
        state: present
        insertafter: EOF

    - name: Source the updated aliases
      ansible.builtin.shell: source ~/.bashrc
      args:
        executable: /bin/bash
