- name: Update Aliases on All VMs
  hosts: all
  become: yes
  tasks:
    - name: Ensure Git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure dos2unix is installed
      ansible.builtin.package:
        name: dos2unix
        state: present

    - name: Clone or update aliases repository
      ansible.builtin.git:
        repo: 'https://github.com/Hrolgar/ansible-playbook.git'
        dest: /root/ansible-playbook
        update: yes
        version: main

    - name: Convert line endings of aliases file to Unix format
      become: yes
      ansible.builtin.shell: |
        dos2unix /root/ansible-playbook/shared/aliases.txt
      args:
        executable: /bin/bash

    - name: Move alias file to the correct location
      become: yes
      ansible.builtin.shell: |
        cp /root/ansible-playbook/shared/aliases.txt /home/hrolgar/.my_aliases
        chown hrolgar:hrolgar /home/hrolgar/.my_aliases
        ls -lah /home/hrolgar/.my_aliases
      register: copy_result
      args:
        executable: /bin/bash

    - name: Ensure .bashrc sources .my_aliases
      become: yes
      become_user: hrolgar
      ansible.builtin.lineinfile:
        path: "/home/hrolgar/.bashrc"
        create: yes
        line: 'source ~/.my_aliases'
        state: present
        insertafter: EOF

    - name: Show .bashrc content
      become: yes
      become_user: hrolgar
      ansible.builtin.shell: |
        tail -n 5 /home/hrolgar/.bashrc
      register: bashrc_content
      args:
        executable: /bin/bash

    - name: Display .bashrc content
      ansible.builtin.debug:
        var: bashrc_content.stdout
