- name: Download Audiobookshelf Backups and Upload to Proton Drive, plus ullrservices Docker Compose Files
  hosts: localhost
  gather_facts: true
  vars:
    remote_path_base: "/opt/nas/apps"
    today: "{{ ansible_date_time.date }}"
    # Local backup folder (inside your Semaphore container)
    local_backup_root: "/services-backups/{{ today }}"
    proton_remote: "proton-remote"
    services:
      - name: audiobookshelf
        backup_path: "{{ remote_path_base }}/audiobookshelf/metadata/backups/*.audiobookshelf"

  tasks:
    #######################################################
    # Initial Setup – Create the full backup directory tree on localhost
    #######################################################
    - name: Ensure parent directory for local backup exists on localhost
      file:
        path: "{{ local_backup_root | dirname }}"
        state: directory
        mode: "0755"
      become: true

    - name: Ensure full local backup directory tree exists on localhost
      shell: "/bin/mkdir -p {{ local_backup_root }}"
      args:
        creates: "{{ local_backup_root }}"
      become: true
      register: mkdir_result

    - name: Verify that the local backup directory exists
      command: /bin/ls -ld {{ local_backup_root }}
      become: true
      register: ls_result

    - debug:
        var: ls_result.stdout
    #######################################################
    # Part 1 – Unified Service Backup Download & Upload
    #######################################################
    - name: Ensure local backup directory for each service exists
      file:
        path: "{{ local_backup_root }}/{{ item.name }}"
        state: directory
        mode: "0755"
      loop: "{{ services }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Find latest backup path for each service
      shell: "ls -t {{ item.backup_path }} | head -n 1"
      delegate_to: ullraudio
      register: latest_backups
      retries: 3
      delay: 5
      until: latest_backups.rc == 0
      loop: "{{ services }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Debug latest backup paths
      debug:
        msg: "{{ latest_backups.results | map(attribute='stdout') | list }}"

    - name: Set fact mapping service names to backup file paths
      set_fact:
        service_backups: >-
          {{
            dict(services | map(attribute='name') | list |
            zip(latest_backups.results | map(attribute='stdout') | list))
          }}

    - name: Set fact for backup filenames (basename)
      set_fact:
        service_backup_names: >-
          {{
            dict(services | map(attribute='name') | list |
            zip(latest_backups.results | map(attribute='stdout') | map('basename') | list))
          }}

    - name: Fetch backup file for each service
      fetch:
        src: "{{ service_backups[item.name] }}"
        dest: "{{ local_backup_root }}/{{ item.name }}/"
        flat: yes
      delegate_to: ullraudio
      loop: "{{ services }}"
      loop_control:
        label: "{{ item.name }}"
      register: fetch_result
      retries: 3
      delay: 5
      until: fetch_result is success

    - name: Upload backup files to Proton Drive for each service
      shell: >
        rclone copy --protondrive-replace-existing-draft=true
        "{{ local_backup_root }}/{{ item.name }}/{{ service_backup_names[item.name] }}"
        "{{ proton_remote }}:backups/{{ today }}/ullraudio/{{ item.name }}"
      loop: "{{ services }}"
      loop_control:
        label: "{{ item.name }}"

    #######################################################
    # Part 2 – Docker Compose Files Backup & Upload
    #######################################################
    - name: Ensure local backup folder for ullraudio exists
      file:
        path: "{{ local_backup_root }}/ullraudio"
        state: directory
        mode: "0755"

    - name: Copy Docker Compose file for audio-compose.yml locally (Folder 38)
      copy:
        src: "/host_apps/portainer_data/compose/38/docker-compose.yml"
        dest: "{{ local_backup_root }}/ullraudio/audio-compose.yml"
        remote_src: yes

    - name: Upload audio-compose.yml to Proton Drive
      shell: >
        rclone copy --protondrive-replace-existing-draft=true
        "{{ local_backup_root }}/ullraudio/audio-compose.yml"
        "{{ proton_remote }}:backups/{{ today }}/ullraudio/"

    #######################################################
    # Final Cleanup – Remove Local Backups
    #######################################################
    - name: Remove local backups
      file:
        path: "{{ local_backup_root }}"
        state: absent
      ignore_errors: true
